### ISSUE TITLE
有几个问题请教下

### ISSUE THREAD

**Issue by iLoveTangY** [skychx/toyRenderer#1]
请问视图矩阵的`Tr`项的最后一列为什么是`-center`而不是`-eye`？
请问代码里的投影矩阵和 GAMES-101 里面闫老师给出来的实质上是一样的吗？能不能稍微解释下？

**Comment by skychx** [comment]
> 请问视图矩阵的`Tr`项的最后一列为什么是`-center`而不是`-eye`？
> 请问代码里的投影矩阵和 GAMES-101 里面闫老师给出来的实质上是一样的吗？能不能稍微解释下？

你好，第一个问题一下子没看懂。我先回答一下第二个问题。第二个投影矩阵和 GAMES101 里推导的实质是一样的，你可以看一下《3D数学基础 图形与游戏开发》这本书，和代码里的形式差不多

**Comment by skychx** [comment]
> > 请问视图矩阵的`Tr`项的最后一列为什么是`-center`而不是`-eye`？
> > 请问代码里的投影矩阵和 GAMES-101 里面闫老师给出来的实质上是一样的吗？能不能稍微解释下？
> 
> 你好，第一个问题一下子没看懂。我先回答一下第二个问题。第二个投影矩阵和 GAMES101 里推导的实质是一样的，你可以看一下《3D数学基础 图形与游戏开发》这本书，和代码里的形式差不多

第一个问题应该说的是[这段代码](https://github.com/skychx/toyRenderer/blob/8fcef61fed895922e35d3ad36dfb35c1e7287e82/tinyrenderer/our_gl.cpp#L16)吧

**Comment by iLoveTangY** [comment]
> > > 请问视图矩阵的`Tr`项的最后一列为什么是`-center`而不是`-eye`？
> > > 请问代码里的投影矩阵和 GAMES-101 里面闫老师给出来的实质上是一样的吗？能不能稍微解释下？
> > 
> > 
> > 你好，第一个问题一下子没看懂。我先回答一下第二个问题。第二个投影矩阵和 GAMES101 里推导的实质是一样的，你可以看一下《3D数学基础 图形与游戏开发》这本书，和代码里的形式差不多
> 
> 第一个问题应该说的是[这段代码](https://github.com/skychx/toyRenderer/blob/8fcef61fed895922e35d3ad36dfb35c1e7287e82/tinyrenderer/our_gl.cpp#L16)吧
嗯嗯，对，`Tr`代表平移吧？我觉得这一项的最后一列应该和 GAMES-101 中推导的一致，使用`-eye`而不是`-center`才对？

**Comment by skychx** [comment]
> > > > 请问视图矩阵的`Tr`项的最后一列为什么是`-center`而不是`-eye`？
> > > > 请问代码里的投影矩阵和 GAMES-101 里面闫老师给出来的实质上是一样的吗？能不能稍微解释下？
> > > 
> > > 
> > > 你好，第一个问题一下子没看懂。我先回答一下第二个问题。第二个投影矩阵和 GAMES101 里推导的实质是一样的，你可以看一下《3D数学基础 图形与游戏开发》这本书，和代码里的形式差不多
> > 
> > 
> > 第一个问题应该说的是[这段代码](https://github.com/skychx/toyRenderer/blob/8fcef61fed895922e35d3ad36dfb35c1e7287e82/tinyrenderer/our_gl.cpp#L16)吧
> > 嗯嗯，对，`Tr`代表平移吧？我觉得这一项的最后一列应该和 GAMES-101 中推导的一致，使用`-eye`而不是`-center`才对？

尴尬😅，这个我需要再检查一下，我当时直接根据[原教程](https://github.com/ssloy/tinyrenderer/wiki/Lesson-5-Moving-the-camera#let-us-create-our-own-glulookat)写了

**Comment by skychx** [comment]
> 请问视图矩阵的`Tr`项的最后一列为什么是`-center`而不是`-eye`？
> 请问代码里的投影矩阵和 GAMES-101 里面闫老师给出来的实质上是一样的吗？能不能稍微解释下？

第一个问题我在 tinyRenderer 的 [issue 12: Probably mistake in lookat](https://github.com/ssloy/tinyrenderer/issues/12#issuecomment-346931309) 中找到答案了，你可以参考看一下
